version: '3.8'

services:
  document-service:
    build: ./document-service
    ports:
      - "8081:8080"
    networks:
      - omnedu-net

  note-service:
    build: ./note-service
    ports:
      - "8082:8080"
    networks:
      - omnedu-net

  video-service:
    build: ./video-service
    ports:
      - "8083:8080"
    networks:
      - omnedu-net

  timer-service:
    build: ./timer-service
    ports:
      - "8084:8080"
    networks:
      - omnedu-net

  ai-chatbot-service:
    build: ./ai-chatbot-service
    ports:
      - "8085:8080"
    networks:
      - omnedu-net

  dashboard-service:
    build: ./dashboard-service
    ports:
      - "8086:8080"
    networks:
      - omnedu-net

  auth-service:
    build: ./auth-service
    ports:
      - "8087:8080"
    networks:
      - omnedu-net

  notification-service:
    build: ./notification-service
    ports:
      - "8088:8080"
    networks:
      - omnedu-net

  configuration-service:
    build: ./configuration-service
    ports:
      - "8089:8080"
    networks:
      - omnedu-net

  logging-service:
    build: ./logging-service
    ports:
      - "8090:8080"
    networks:
      - omnedu-net

  user-service:
    build: ./user-service
    ports:
      - "8091:8080"
    networks:
      - omnedu-net

  module-service:
    build: ./module-service
    ports:
      - "8092:8080"
    networks:
      - omnedu-net

  theme-service:
    build: ./theme-service
    ports:
      - "8093:8080"
    networks:
      - omnedu-net

  preference-service:
    build: ./preference-service
    ports:
      - "8094:8080"
    networks:
      - omnedu-net

  task-service:
    build: ./task-service
    ports:
      - "8095:8080"
    networks:
      - omnedu-net

  statistics-service:
    build: ./statistics-service
    ports:
      - "8096:8080"
    networks:
      - omnedu-net

networks:
  omnedu-net:
    driver: bridge
