spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # Public Auth Service Routes (No Authentication Required)
        - id: auth-service-public
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/register,/api/auth/login,/api/auth/verify

        # Notes Service - Protected Routes
        - id: notes-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/notes/**
        
        # videos Service - Protected Routes
        - id: videos-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/videos/**
          
        # docs Service - Protected Routes
        - id: documents-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/documents/**
        
        # timer Service - Protected Routes
        - id: timer-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/timer/**
        
        # tasks Service - Protected Routes
        - id: tasks-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/tasks/**





server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.omnedu.gateway.filter: TRACE

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway/routes  # Allow these endpoints to be exposed
    gateway:
      access: read  # Enable Gateway actuator for routes
