spring:
  application:
    name: timer-service
  datasource:
    url: jdbc:mysql://localhost:3306/timer_db?createDatabaseIfNotExist=true
    username: root
    password: wearetheborg
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

logging:
  level:
    org.springframework.web: DEBUG
jwt:
    secret: sVRs1xcOZIMjT1ArjTkpfurGNxgeTJV2uJXU1iEB0LrW2fB5k0kfKDG0/AR66ksVpmwHzll4+c4fYw+TuuU67A==

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false # If not using Hystrix
  request:
    interceptor:
      enabled: true
task:
  service:
    url: http://localhost:8086 # This should match your gateway route to task service