spring:
  application:
    name: notes-service
  datasource:
    url: jdbc:mysql://localhost:3306/notes_db?createDatabaseIfNotExist=true
    username: root
    password: wearetheborg
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
jwt:
    secret: sVRs1xcOZIMjT1ArjTkpfurGNxgeTJV2uJXU1iEB0LrW2fB5k0kfKDG0/AR66ksVpmwHzll4+c4fYw+TuuU67A==